In [ ]:
%pip install -q bert_score
%pip install -q ragas

In [6]:
from dotenv import load_dotenv
load_dotenv()

True

In [3]:
questions = [
    "아진산업의 최초 설립일은 언제인가요?",
    "아진산업의 2025년 매출액은 얼마인가요?",
    "아진산업의 본사 위치는 어디인가요?",
]

ground_truths = [
    "아진산업은 1978년 5월 31일 창립하였습니다.",
    "아진산업은 2025년에 1조 88억 6783만원의 매출 실적을 달성했습니다.",
    "아진산업의 본사는 경상북도 경산시 진량읍에 있습니다."
]

In [4]:
from langchain_community.document_loaders import PyPDFLoader
loader = PyPDFLoader("..\\docs\\knu.pdf")
documents = loader.load()

C:\Users\USER\AppData\Local\Temp\ipykernel_32288\3768569987.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFLoader

In [7]:
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
llm = ChatOpenAI(model="gpt-5.4-nano")
embedding = OpenAIEmbeddings(model="text-embedding-3-small")

In [8]:
from langchain_chroma import Chroma
vectorstore = Chroma.from_documents(
    documents=documents,
    embedding=embedding
)
retriever = vectorstore.as_retriever()

In [9]:
def format_docs(docs):
    return "\n".join(doc.page_content for doc in docs)

In [10]:
from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_template("""
    다음 문맥만 사용하여 질문에 한 문장으로 답하세요.
    문맥에서 알 수 없는 내용은 모른다고 답하세요.
    [문맥] {context}
    [질문] {question}
""")

In [11]:
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
rag_chain = (
    {
        "context": retriever | format_docs,
        "question": RunnablePassthrough()
    }
    | prompt
    | llm
    | StrOutputParser()
)

In [12]:
contexts = []
answers = []
for question in questions:
    docs = retriever.invoke(question)
    contexts.append([doc.page_content for doc in docs])
    answer = rag_chain.invoke(question)
    answers.append(answer)

In [13]:
import pandas as pd
from bert_score import score

P, R, F1 = score(
    cands=answers,
    refs=ground_truths,
    lang="ko",
    verbose=True
)

df_bertscore = pd.DataFrame({
    "question": questions,
    "ground_truth": ground_truths,
    "answer": answers,
    "bertscore_precision": P.tolist(),
    "bertscore_recall": R.tolist(),
    "bertscore_f1": F1.tolist(),
})

df_bertscore

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

calculating scores...
computing bert embedding.

  0%|          | 0/1 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/1 [00:00<?, ?it/s]

done in 1.67 seconds, 1.79 sentences/sec

,question,ground_truth,answer,bertscore_precision,bertscore_recall,bertscore_f1
0,아진산업의 최초 설립일은 언제인가요?,아진산업은 1978년 5월 31일 창립하였습니다.,문맥에서 아진산업의 최초 설립일에 대한 정보가 없어 모른다고 답하겠습니다.,0.739745,0.808107,0.772416
1,아진산업의 2025년 매출액은 얼마인가요?,아진산업은 2025년에 1조 88억 6783만원의 매출 실적을 달성했습니다.,문맥에는 아진산업의 2025년 매출액 정보가 없으므로 모릅니다.,0.779742,0.732850,0.755569
2,아진산업의 본사 위치는 어디인가요?,아진산업의 본사는 경상북도 경산시 진량읍에 있습니다.,문맥에서 아진산업의 본사 위치는 알 수 없으므로 모른다고 답합니다.,0.750971,0.772866,0.761761

In [14]:
df_bertscore["bertscore_f1"].mean()

np.float64(0.7632489204406738)

In [15]:
from datasets import Dataset

ragas_data = {
    "question": questions,
    "answer": answers,
    "contexts": contexts,
    "ground_truth": ground_truths,
}

dataset = Dataset.from_dict(ragas_data)
dataset

Dataset({
    features: ['question', 'answer', 'contexts', 'ground_truth'],
    num_rows: 3
})

In [16]:
dataset[0]

{'question': '아진산업의 최초 설립일은 언제인가요?',
 'answer': '문맥에서 아진산업의 최초 설립일에 대한 정보가 없어 모른다고 답하겠습니다.',
 'contexts': ['- 118 -\n구분계열학과 또는 전공명입학정원 및 학과 또는 전공설치 여부석사과정2026학년도2025학년도2024학년도행 정 대 학 원인문․사회계열공 공 관 리 전 공○○○정 책․도 시 전 공○○○지 방 자 치 전 공○○○법 무․안 전 전 공○○○입학정원606060경 영 대 학 원인문․사회계열경 영 학 전 공○○○글 로 벌M B A전 공○○○입학정원120120120보 건 대 학 원자연과학계열역 학 및 건 강 증 진 학 과○○○보 건 관 리 학 과○○○입학정원404040산 업 대 학 원공 학 계 열산 업 공 학 과회 로  및  시 스 템 전 공○○○제 어  및  계 측 공 학 전 공○○○정 보 통 신 공 학 전 공○○○반 도 체 공 학 전 공○○○컴 퓨 터 공 학 전 공○○○기 계 공 학 전 공○○○응 용 화 학 전 공X○○금 속 신 소 재 공 학 전 공○○○건 축 공 학 전 공○○○토 목 공 학 전 공○○○전 기 공 학 전 공○○○화 학 공 학 전 공X○○응 용 화 학 공 학 전 공○XX고 분 자 공 학 전 공○○○무 기 재 료 공 학 전 공○○○섬 유 시 스 템 공 학 전 공○○○환 경 공 학 전 공○○○기 술 정 책 전 공○○○입학정원858585스 마 트 농 생 명식품융합대학원자연과학계열농 업 자 원 학 전 공○○○식 품 산 업 공 학 전 공○○○농 업 공 학 전 공○○○농 촌 개 발 전 공○○○농 산 물 안 전 성 학 전 공○○○농 업 정 책 및 유 통 전 공○○○환 경 조 경 학 전 공○○○스 마 트 농 업 시 스 템 공 학 전 공○○○입학정원353538',
  '- 131 -\n￭ 학사과정\n※ 과학기술대학 산업기계공학과, IT대학 ICT융합학과는 3학년 편입과정으로 운영※ 전자공학부 모바일AI공학전공은 학·석사통합과정으로 운영 \n관리 대학계열학과명[협약기관] 운영학과수여학위입학정원학사과정2027학년도2026학년도2025학년도2024학년도\nIT대학공학계열전 자 공 학 부모 바 일 공 학 전 공[삼 성 전 자(주) ]전 자 공 학 부공 학 사- 303030I C T융 합 학 과[대 경I C T산 업협회 및 회원기업]컴 퓨 터 학 부공 학 사2020전 자 공 학 부모 바 일A I공 학 전 공[삼 성 전 자(주) ]전 자 공 학 부공 학 사(공학석사)20과학기술대학공학계열산 업 기 계 공 학 과[한국산업인력공단 및 P- TECH대학 참여업체]정밀기계공학과공 학 사40404040입학정원80907070',
  '- 86 -\n계열학과(부)명 입학정원 및 학과 설치 여부석  사  과  정박  사  과  정2026학년도2025학년도2026학년도2025학년도1학기2학기1학기2학기1학기2학기1학기2학기해 양 학 과○○○○응 용 생 물 학 과○○○○식품공학부(식품생물공학전공, ○○○○식품소재공학전공,식품응용공학전공)원 예 학 과○○○○농 업 토 목 공 학 과○○○○생 물 산 업 기 계 공 학 과○○○○바 이 오 섬 유 소 재 학 과○○○○임  학  과○○○○임 산 공 학 과○○○○조 경 학 과○○○○수 학 교 육 학 과○○○○과 학 교 육 학 과○○○○가 정 교 육 학 과○○○○아 동 가 족 학 과○○○○의 류 학 과○○○○식 품 영 양 학 과○○○○간 호 학 과○○○○보 건 학 과☓☓○○의 과 학 과○○○○치 의 과 학 과○○○○약  학  과 ○○○○의 생 명 융 합 공 학 과○○○○농 생 명 융 합 공 학 과○○○○응 용 생 명 과 학 과○○○○환 동 해 안 융 복 합 학 과○○○○혁 신 신 약 학 과○☓○○☓공 학 계 열첨 단 소 재공 학 부(금속재료공학전공, ○○○○신소재공학전공)기 계 공 학 과○○○○건 축 학 과○○○○건 설 환 경에너지공학부(건 축 공 학 전 공, ○○○○토 목 공 학 전 공,환 경 공 학 전 공,에너지공학전공)응 용 화 학 공 학 부○○○○고 분 자 공 학 과○○○○섬 유 시 스 템 공 학 과○○○○컴 퓨 터 학 부○○○○인 공 지 능 학 과○○○○로봇 및 스마트시스템공학과○○○○전 자 전 기 공 학 부○○○○전 자 전 기 공 학 부*(결손인원을 활용한 증원 정원)23231111데 이 터 융 합 컴 퓨 팅 학 과○○○○과 학 기 술실용공학부(과학기술정책전공, ○○○○과학기술실무전공,과학기술창업전공)융 합 안 전 공 학 과○○☓☓',
  '- 79 -\n과정협약기관참여학과명입학정원 및 협약기관 설치 여부석  사  과  정박  사  과  정2026학년도2025학년도2026학년도2025학년도1학기2학기1학기2학기1학기2학기1학기2학기\n농 촌 진 흥 청응 용 생 명 과 학 과○○○○응 용 생 물 학 과식 품 공 학 부원 예 학 과생 물 산 업 기 계 공 학 과바 이 오 섬 유 소 재 학 과농 업 경 제 학 과약 학 과축 산B T학 과생 명 과 학 부\n한국에너지기술연구원첨 단 소 재 공 학 부○○○○기 계 공 학 과건 축 학 과건 설 환 경 에 너 지 공 학 부응 용 화 학 공 학 부전 자 전 기 공 학 부컴 퓨 터 학 부정 밀 기 계 공 학 과생 물 산 업 기 계 공 학 과에 너 지 화 학 공 학 과\n한국원자력연구원\n물 리 학 과\n○○○○\n화 학 과응 용 생 명 과 학 과응 용 생 물 학 과식 품 공 학 부첨 단 소 재 공 학 부기 계 공 학 과응 용 화 학 공 학 부전 자 전 기 공 학 부컴 퓨 터 학 부건 설 환 경 에 너 지 공 학 부(환 경 공 학 전 공,에 너 지 공 학 전 공)정 밀 기 계 공 학 과생 물 산 업 기 계 공 학 과에 너 지 화 학 공 학 과한국염색기술연구소섬 유 시 스 템 공 학 과○○○○첨 단 소 재 공 학 부(신 소 재 공 학 전 공)\n한국생산기술연구원\n첨 단 소 재 공 학 부\n○○○○기 계 공 학 과건 축 학 과건 설 환 경 에 너 지 공 학 부응 용 화 학 공 학 부고 분 자 공 학 과섬 유 시 스 템 공 학 과전 자 전 기 공 학 부컴 퓨 터 학 부의 과 학 과정 밀 기 계 공 학 과'],
 'ground_truth': '아진산업은 1978년 5월 31일 창립하였습니다.'}

In [ ]:
from ragas import evaluate
from ragas.metrics import (
    faithfulness, answer_relevancy,
    context_precision, context_recall,
)

ragas_result = evaluate(
    dataset=dataset,
    metrics=[
        faithfulness,
        answer_relevancy,
        context_precision,
        context_recall,
    ],
    llm=llm,
    embeddings=embedding,
)
ragas_result

Evaluating:   0%|          | 0/12 [00:00<?, ?it/s]

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

{'faithfulness': 0.8333, 'answer_relevancy': 0.0000, 'context_precision': 0.0000, 'context_recall': 0.0000}

In [18]:
df_ragas = ragas_result.to_pandas()
df_ragas

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,context_precision,context_recall
0,아진산업의 최초 설립일은 언제인가요?,[- 118 -\n구분계열학과 또는 전공명입학정원 및 학과 또는 전공설치 여부석사과...,문맥에서 아진산업의 최초 설립일에 대한 정보가 없어 모른다고 답하겠습니다.,아진산업은 1978년 5월 31일 창립하였습니다.,NaN,NaN,NaN,NaN
1,아진산업의 2025년 매출액은 얼마인가요?,[- 45 -\n[별표 1]<삭제 2006.9.29>[별표 2] <삭제 2020. ...,문맥에는 아진산업의 2025년 매출액 정보가 없으므로 모릅니다.,아진산업은 2025년에 1조 88억 6783만원의 매출 실적을 달성했습니다.,NaN,NaN,NaN,NaN
2,아진산업의 본사 위치는 어디인가요?,[- 102 -\n20. 2013학년도 대학원 학생정원 조정내용<2013. 3. 1...,문맥에서 아진산업의 본사 위치는 알 수 없으므로 모른다고 답합니다.,아진산업의 본사는 경상북도 경산시 진량읍에 있습니다.,NaN,NaN,NaN,NaN

In [19]:
df_eval = df_ragas.copy()

df_eval["bertscore_precision"] = df_bertscore["bertscore_precision"]
df_eval["bertscore_recall"] = df_bertscore["bertscore_recall"]
df_eval["bertscore_f1"] = df_bertscore["bertscore_f1"]

df_eval[
    [
        "question",
        "ground_truth",
        "answer",
        "bertscore_f1",
        "faithfulness",
        "answer_relevancy",
        "context_precision",
        "context_recall",
    ]
]

KeyError: "['question', 'ground_truth', 'answer'] not in index"

In [ ]:
score_columns = [
    "bertscore_f1",
    "faithfulness",
    "answer_relevancy",
    "context_precision",
    "context_recall",
]

df_eval[score_columns].mean()

In [ ]:
import sys
print(sys.executable)
print(sys.version)

In [15]:
import sys
!{sys.executable} -m pip show bert-score
!{sys.executable} -m pip show ragas
!{sys.executable} -m pip show langchain-google-vertexai

Name: bert-score
Version: 0.3.13
Summary: PyTorch implementation of BERT score
Home-page: https://github.com/Tiiiger/bert_score
Author: Tianyi Zhang*, Varsha Kishore*, Felix Wu*, Kilian Q. Weinberger, and Yoav Artzi
Author-email: tzhang@asapp.com
License: MIT
Location: d:\_knukdt\knu-kdt-dev\.kdtenv\Lib\site-packages
Requires: matplotlib, numpy, packaging, pandas, requests, torch, tqdm, transformers
Required-by:
Name: ragas
Version: 0.4.3
Summary: Evaluation framework for RAG and LLM applications
Home-page: https://github.com/vibrantlabsai/ragas
Author:
Author-email:
License: Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "Legal Entity" shall mean the union of the acting entity and all
      other entities that control, are controlled by, or are under common
      control with that entity. For the purposes of this definition,
      "control" means (i) the power, direct or indirect, to cause the
      direction or management of such entity, whether by contract or
      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      outstanding shares, or (iii) beneficial ownership of such entity.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      "Source" form shall mean the preferred form for making modifications,
      including but not limited to software source code, documentation
      source, and configuration files.

      "Object" form shall mean any form resulting from mechanical
      transformation or translation of a Source form, including but
      not limited to compiled object code, generated documentation,
      and conversions to other media types.

      "Work" shall mean the work of authorship, whether in Source or
      Object form, made available under the License, as indicated by a
      copyright notice that is included in or attached to the work
      (an example is provided in the Appendix below).

      "Derivative Works" shall mean any work, whether in Source or Object
      form, that is based on (or derived from) the Work and for which the
      editorial revisions, annotations, elaborations, or other modifications
      represent, as a whole, an original work of authorship. For the purposes
      of this License, Derivative Works shall not include works that remain
      separable from, or merely link (or bind by name) to the interfaces of,
      the Work and Derivative Works thereof.

      "Contribution" shall mean any work of authorship, including
      the original version of the Work and any modifications or additions
      to that Work or Derivative Works thereof, that is intentionally
      submitted to Licensor for inclusion in the Work by the copyright owner
      or by an individual or Legal Entity authorized to submit on behalf of
      the copyright owner. For the purposes of this definition, "submitted"
      means any form of electronic, verbal, or written communication sent
      to the Licensor or its representatives, including but not limited to
      communication on electronic mailing lists, source code control systems,
      and issue tracking systems that are managed by, or on behalf of, the
      Licensor for the purpose of discussing and improving the Work, but
      excluding communication that is conspicuously marked or otherwise
      designated in writing by the copyright owner as "Not a Contribution."

      "Contributor" shall mean Licensor and any individual or Legal Entity
      on behalf of whom a Contribution has been received by Licensor and
      subsequently incorporated within the Work.

   2. Grant of Copyright License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      copyright license to reproduce, prepare Derivative Works of,
      publicly display, publicly perform, sublicense, and distribute the
      Work and such Derivative Works in Source or Object form.

   3. Grant of Patent License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      (except as stated in this section) patent license to make, have made,
      use, offer to sell, sell, import, and otherwise transfer the Work,
      where such license applies only to those patent claims licensable
      by such Contributor that are necessarily infringed by their
      Contribution(s) alone or by combination of their Contribution(s)
      with the Work to which such Contribution(s) was submitted. If You
      institute patent litigation against any entity (including a
      cross-claim or counterclaim in a lawsuit) alleging that the Work
      or a Contribution incorporated within the Work constitutes direct
      or contributory patent infringement, then any patent licenses
      granted to You under this License for that Work shall terminate
      as of the date such litigation is filed.

   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

      You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use, reproduction, or distribution of Your modifications, or
      for any such Derivative Works as a whole, provided Your use,
      reproduction, and distribution of the Work otherwise complies with
      the conditions stated in this License.

   5. Submission of Contributions. Unless You explicitly state otherwise,
      any Contribution intentionally submitted for inclusion in the Work
      by You to the Licensor shall be under the terms and conditions of
      this License, without any additional terms or conditions.
      Notwithstanding the above, nothing herein shall supersede or modify
      the terms of any separate license agreement you may have executed
      with Licensor regarding such Contributions.

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

   7. Disclaimer of Warranty. Unless required by applicable law or
      agreed to in writing, Licensor provides the Work (and each
      Contributor provides its Contributions) on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
      implied, including, without limitation, any warranties or conditions
      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
      PARTICULAR PURPOSE. You are solely responsible for determining the
      appropriateness of using or redistributing the Work and assume any
      risks associated with Your exercise of permissions under this License.

   8. Limitation of Liability. In no event and under no legal theory,
      whether in tort (including negligence), contract, or otherwise,
      unless required by applicable law (such as deliberate and grossly
      negligent acts) or agreed to in writing, shall any Contributor be
      liable to You for damages, including any direct, indirect, special,
      incidental, or consequential damages of any character arising as a
      result of this License or out of the use or inability to use the
      Work (including but not limited to damages for loss of goodwill,
      work stoppage, computer failure or malfunction, or any and all
      other commercial damages or losses), even if such Contributor
      has been advised of the possibility of such damages.

   9. Accepting Warranty or Additional Liability. While redistributing
      the Work or Derivative Works thereof, You may choose to offer,
      and charge a fee for, acceptance of support, warranty, indemnity,
      or other liability obligations and/or rights consistent with this
      License. However, in accepting such obligations, You may act only
      on Your own behalf and on Your sole responsibility, not on behalf
      of any other Contributor, and only if You agree to indemnify,
      defend, and hold each Contributor harmless for any liability
      incurred by, or claims asserted against, such Contributor by reason
      of your accepting any such warranty or additional liability.

   END OF TERMS AND CONDITIONS

   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright [2023] [Vibrant Labs]

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

Location: d:\_knukdt\knu-kdt-dev\.kdtenv\Lib\site-packages
Requires: appdirs, datasets, diskcache, instructor, langchain, langchain-community, langchain-core, langchain_openai, nest-asyncio, networkx, numpy, openai, pillow, pydantic, rich, scikit-network, tiktoken, tqdm, typer
Required-by:
Name: langchain-google-vertexai
Version: 3.2.4
Summary: An integration package connecting Google VertexAI and LangChain
Home-page: https://docs.langchain.com/oss/python/integrations/providers/google
Author:
Author-email:
License: MIT
Location: d:\_knukdt\knu-kdt-dev\.kdtenv\Lib\site-packages
Requires: bottleneck, google-cloud-aiplatform, google-cloud-storage, google-cloud-vectorsearch, httpx, httpx-sse, langchain-core, numexpr, pyarrow, pydantic, validators
Required-by:

In [ ]:
import sys

!{sys.executable} -m pip install bert-score ragas langchain-google-vertexai

In [ ]:
import os
os._exit(00)